#include "cpu.h"

Cpu::opinfo_t Cpu::opmap[256] = {
        // 0x00
        { &Cpu::NOP, "NOP", 1 },
        { &Cpu::LDBCnn, "LDBCnn", 3 },
        { &Cpu::LDBCmA, "LDBCmA", 2 },
        { &Cpu::INCBC, "INCBC", 1 },
        { &Cpu::INCr_b, "INCr_b", 1 },
        { &Cpu::DECr_b, "DECr_b", 1 },
        { &Cpu::LDrn_b, "LDrn_b", 2 },
        { &Cpu::RLCA, "RLCA", 1 },
        { &Cpu::LDmmSP, "LDmmSP", 3 },
        { &Cpu::ADDHLBC, "ADDHLBC", 1 },
        { &Cpu::LDABCm, "LDABCm", 1 },
        { &Cpu::DECBC, "DECBC", 1 },
        { &Cpu::INCr_c, "INCr_c", 1 },
        { &Cpu::DECr_c, "DECr_c", 1 },
        { &Cpu::LDrn_c, "LDrn_c", 2 },
        { &Cpu::RRCA, "RRCA", 1 },

        // 0x10
        { &Cpu::STOP, "STOP", 2 },
        { &Cpu::LDDEnn, "LDDEnn", 3 },
        { &Cpu::LDDEmA, "LDDEmA", 2 },
        { &Cpu::INCDE, "INCDE", 1 },
        { &Cpu::INCr_d, "INCr_d", 1 },
        { &Cpu::DECr_d, "DECr_d", 1 },
        { &Cpu::LDrn_d, "LDrn_d", 2 },
        { &Cpu::RLA, "RLA", 1 },
        { &Cpu::JRn, "JRn", 2 },
        { &Cpu::ADDHLDE, "ADDHLDE", 1 },
        { &Cpu::LDADEm, "LDADEm", 1 },
        { &Cpu::DECDE, "DECDE", 1 },
        { &Cpu::INCr_e, "INCr_e", 1 },
        { &Cpu::DECr_e, "DECr_e", 1 },
        { &Cpu::LDrn_e, "LDrn_e", 2 },
        { &Cpu::RRA, "RRA", 1 },

        // 0x20
        { &Cpu::JRNZn, "JRNZn", 2 },
        { &Cpu::LDHLnn, "LDHLnn", 3 },
        { &Cpu::LDHLIA, "LDHLIA", 1 },
        { &Cpu::INCHL, "INCHL", 1 },
        { &Cpu::INCr_h, "INCr_h", 1 },
        { &Cpu::DECr_h, "DECr_h", 1 },
        { &Cpu::LDrn_h, "LDrn_h", 2 },
        { &Cpu::DAA, "DAA", 1 },
        { &Cpu::JRZn, "JRZn", 2 },
        { &Cpu::ADDHLHL, "ADDHLHL", 1 },
        { &Cpu::LDAHLI, "LDAHLI", 1 },
        { &Cpu::DECHL, "DECHL", 1 },
        { &Cpu::INCr_l, "INCr_l", 1 },
        { &Cpu::DECr_l, "DECr_l", 1 },
        { &Cpu::LDrn_l, "LDrn_l", 2 },
        { &Cpu::CPL, "CPL", 1 },

        // 0x30
        { &Cpu::JRNCn, "JRNCn", 2 },
        { &Cpu::LDSPnn, "LDSPnn", 3 },
        { &Cpu::LDHLDA, "LDHLDA", 1 },
        { &Cpu::INCSP, "INCSP", 1 },
        { &Cpu::INCHLm, "INCHLm", 1 },
        { &Cpu::DECHLm, "DECHLm", 1 },
        { &Cpu::LDHLmn, "LDHLmn", 2 },
        { &Cpu::SCF, "SCF", 1 },
        { &Cpu::JRCn, "JRCn", 2 },
        { &Cpu::ADDHLSP, "ADDHLSP", 1 },
        { &Cpu::LDAHLD, "LDAHLD", 1 },
        { &Cpu::DECSP, "DECSP", 1 },
        { &Cpu::INCr_a, "INCr_a", 1 },
        { &Cpu::DECr_a, "DECr_a", 1 },
        { &Cpu::LDrn_a, "LDrn_a", 2 },
        { &Cpu::CCF, "CCF", 1 },

        // 0x40
        { &Cpu::LDrr_bb, "LDrr_bb", 1 },
        { &Cpu::LDrr_bc, "LDrr_bc", 1 },
        { &Cpu::LDrr_bd, "LDrr_bd", 1 },
        { &Cpu::LDrr_be, "LDrr_be", 1 },
        { &Cpu::LDrr_bh, "LDrr_bh", 1 },
        { &Cpu::LDrr_bl, "LDrr_bl", 1 },
        { &Cpu::LDrHLm_b, "LDrHLm_b", 1 },
        { &Cpu::LDrr_ba, "LDrr_ba", 1 },
        { &Cpu::LDrr_cb, "LDrr_cb", 1 },
        { &Cpu::LDrr_cc, "LDrr_cc", 1 },
        { &Cpu::LDrr_cd, "LDrr_cd", 1 },
        { &Cpu::LDrr_ce, "LDrr_ce", 1 },
        { &Cpu::LDrr_ch, "LDrr_ch", 1 },
        { &Cpu::LDrr_cl, "LDrr_cl", 1 },
        { &Cpu::LDrHLm_c, "LDrHLm_c", 1 },
        { &Cpu::LDrr_ca, "LDrr_ca", 1 },

        // 0x50
        { &Cpu::LDrr_db, "LDrr_db", 1 },
        { &Cpu::LDrr_dc, "LDrr_dc", 1 },
        { &Cpu::LDrr_dd, "LDrr_dd", 1 },
        { &Cpu::LDrr_de, "LDrr_de", 1 },
        { &Cpu::LDrr_dh, "LDrr_dh", 1 },
        { &Cpu::LDrr_dl, "LDrr_dl", 1 },
        { &Cpu::LDrHLm_d, "LDrHLm_d", 1 },
        { &Cpu::LDrr_da, "LDrr_da", 1 },
        { &Cpu::LDrr_eb, "LDrr_eb", 1 },
        { &Cpu::LDrr_ec, "LDrr_ec", 1 },
        { &Cpu::LDrr_ed, "LDrr_ed", 1 },
        { &Cpu::LDrr_ee, "LDrr_ee", 1 },
        { &Cpu::LDrr_eh, "LDrr_eh", 1 },
        { &Cpu::LDrr_el, "LDrr_el", 1 },
        { &Cpu::LDrHLm_e, "LDrHLm_e", 1 },
        { &Cpu::LDrr_ea, "LDrr_ea", 1 },

        // 0x60
        { &Cpu::LDrr_hb, "LDrr_hb", 1 },
        { &Cpu::LDrr_hc, "LDrr_hc", 1 },
        { &Cpu::LDrr_hd, "LDrr_hd", 1 },
        { &Cpu::LDrr_he, "LDrr_he", 1 },
        { &Cpu::LDrr_hh, "LDrr_hh", 1 },
        { &Cpu::LDrr_hl, "LDrr_hl", 1 },
        { &Cpu::LDrHLm_h, "LDrHLm_h", 1 },
        { &Cpu::LDrr_ha, "LDrr_ha", 1 },
        { &Cpu::LDrr_lb, "LDrr_lb", 1 },
        { &Cpu::LDrr_lc, "LDrr_lc", 1 },
        { &Cpu::LDrr_ld, "LDrr_ld", 1 },
        { &Cpu::LDrr_le, "LDrr_le", 1 },
        { &Cpu::LDrr_lh, "LDrr_lh", 1 },
        { &Cpu::LDrr_ll, "LDrr_ll", 1 },
        { &Cpu::LDrHLm_l, "LDrHLm_l", 1 },
        { &Cpu::LDrr_la, "LDrr_la", 1 },

        // 0x70
        { &Cpu::LDHLmr_b, "LDHLmr_b", 1 },
        { &Cpu::LDHLmr_c, "LDHLmr_c", 1 },
        { &Cpu::LDHLmr_d, "LDHLmr_d", 1 },
        { &Cpu::LDHLmr_e, "LDHLmr_e", 1 },
        { &Cpu::LDHLmr_h, "LDHLmr_h", 1 },
        { &Cpu::LDHLmr_l, "LDHLmr_l", 1 },
        { &Cpu::HALT, "HALT", 1 },
        { &Cpu::LDHLmr_a, "LDHLmr_a", 1 },
        { &Cpu::LDrr_ab, "LDrr_ab", 1 },
        { &Cpu::LDrr_ac, "LDrr_ac", 1 },
        { &Cpu::LDrr_ad, "LDrr_ad", 1 },
        { &Cpu::LDrr_ae, "LDrr_ae", 1 },
        { &Cpu::LDrr_ah, "LDrr_ah", 1 },
        { &Cpu::LDrr_al, "LDrr_al", 1 },
        { &Cpu::LDrHLm_a, "LDrHLm_a", 1 },
        { &Cpu::LDrr_aa, "LDrr_aa", 1 },

        // 0x80
        { &Cpu::ADDr_b, "ADDr_b", 1 },
        { &Cpu::ADDr_c, "ADDr_c", 1 },
        { &Cpu::ADDr_d, "ADDr_d", 1 },
        { &Cpu::ADDr_e, "ADDr_e", 1 },
        { &Cpu::ADDr_h, "ADDr_h", 1 },
        { &Cpu::ADDr_l, "ADDr_l", 1 },
        { &Cpu::ADDHL, "ADDHL", 1 },
        { &Cpu::ADDr_a, "ADDr_a", 1 },
        { &Cpu::ADCr_b, "ADCr_b", 1 },
        { &Cpu::ADCr_c, "ADCr_c", 1 },
        { &Cpu::ADCr_d, "ADCr_d", 1 },
        { &Cpu::ADCr_e, "ADCr_e", 1 },
        { &Cpu::ADCr_h, "ADCr_h", 1 },
        { &Cpu::ADCr_l, "ADCr_l", 1 },
        { &Cpu::ADCHL, "ADCHL", 1 },
        { &Cpu::ADCr_a, "ADCr_a", 1 },

        // 0x90
        { &Cpu::SUBr_b, "SUBr_b", 1 },
        { &Cpu::SUBr_c, "SUBr_c", 1 },
        { &Cpu::SUBr_d, "SUBr_d", 1 },
        { &Cpu::SUBr_e, "SUBr_e", 1 },
        { &Cpu::SUBr_h, "SUBr_h", 1 },
        { &Cpu::SUBr_l, "SUBr_l", 1 },
        { &Cpu::SUBHL, "SUBHL", 1 },
        { &Cpu::SUBr_a, "SUBr_a", 1 },
        { &Cpu::SBCr_b, "SBCr_b", 1 },
        { &Cpu::SBCr_c, "SBCr_c", 1 },
        { &Cpu::SBCr_d, "SBCr_d", 1 },
        { &Cpu::SBCr_e, "SBCr_e", 1 },
        { &Cpu::SBCr_h, "SBCr_h", 1 },
        { &Cpu::SBCr_l, "SBCr_l", 1 },
        { &Cpu::SBCHL, "SBCHL", 1 },
        { &Cpu::SBCr_a, "SBCr_a", 1 },

        // 0xA0
        { &Cpu::ANDr_b, "ANDr_b", 1 },
        { &Cpu::ANDr_c, "ANDr_c", 1 },
        { &Cpu::ANDr_d, "ANDr_d", 1 },
        { &Cpu::ANDr_e, "ANDr_e", 1 },
        { &Cpu::ANDr_h, "ANDr_h", 1 },
        { &Cpu::ANDr_l, "ANDr_l", 1 },
        { &Cpu::ANDHL, "ANDHL", 1 },
        { &Cpu::ANDr_a, "ANDr_a", 1 },
        { &Cpu::XORr_b, "XORr_b", 1 },
        { &Cpu::XORr_c, "XORr_c", 1 },
        { &Cpu::XORr_d, "XORr_d", 1 },
        { &Cpu::XORr_e, "XORr_e", 1 },
        { &Cpu::XORr_h, "XORr_h", 1 },
        { &Cpu::XORr_l, "XORr_l", 1 },
        { &Cpu::XORHL, "XORHL", 1 },
        { &Cpu::XORr_a, "XORr_a", 1 },

        // 0xB0
        { &Cpu::ORr_b, "ORr_b", 1 },
        { &Cpu::ORr_c, "ORr_c", 1 },
        { &Cpu::ORr_d, "ORr_d", 1 },
        { &Cpu::ORr_e, "ORr_e", 1 },
        { &Cpu::ORr_h, "ORr_h", 1 },
        { &Cpu::ORr_l, "ORr_l", 1 },
        { &Cpu::ORHL, "ORHL", 1 },
        { &Cpu::ORr_a, "ORr_a", 1 },
        { &Cpu::CPr_b, "CPr_b", 1 },
        { &Cpu::CPr_c, "CPr_c", 1 },
        { &Cpu::CPr_d, "CPr_d", 1 },
        { &Cpu::CPr_e, "CPr_e", 1 },
        { &Cpu::CPr_h, "CPr_h", 1 },
        { &Cpu::CPr_l, "CPr_l", 1 },
        { &Cpu::CPHL, "CPHL", 1 },
        { &Cpu::CPr_a, "CPr_a", 1 },

        // 0xC0
        { &Cpu::RETNZ, "RETNZ", 1 },
        { &Cpu::POPBC, "POPBC", 1 },
        { &Cpu::JPNZnn, "JPNZnn", 3 },
        { &Cpu::JPnn, "JPnn", 3 },
        { &Cpu::CALLNZnn, "CALLNZnn", 3 },
        { &Cpu::PUSHBC, "PUSHBC", 1 },
        { &Cpu::ADDn, "ADDn", 2 },
        { &Cpu::RST00, "RST00", 1 },
        { &Cpu::RETZ, "RETZ", 1 },
        { &Cpu::RET, "RET", 1 },
        { &Cpu::JPZnn, "JPZnn", 3 },
        { &Cpu::MAPcb, "MAPcb", 1 },
        { &Cpu::CALLZnn, "CALLZnn", 3 },
        { &Cpu::CALLnn, "CALLnn", 3 },
        { &Cpu::ADCn, "ADCn", 2 },
        { &Cpu::RST08, "RST08", 1 },

        // 0xD0
        { &Cpu::RETNC, "RETNC", 1 },
        { &Cpu::POPDE, "POPDE", 1 },
        { &Cpu::JPNCnn, "JPNCnn", 3 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::CALLNCnn, "CALLNCnn", 3 },
        { &Cpu::PUSHDE, "PUSHDE", 1 },
        { &Cpu::SUBn, "SUBn", 2 },
        { &Cpu::RST10, "RST10", 1 },
        { &Cpu::RETC, "RETC", 1 },
        { &Cpu::RETI, "RETI", 1 },
        { &Cpu::JPCnn, "JPCnn", 3 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::CALLCnn, "CALLCnn", 3 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::SBCn, "SBCn", 2 },
        { &Cpu::RST18, "RST18", 1 },

        // 0xE0
        { &Cpu::LDIOnA, "LDIOnA", 2 },
        { &Cpu::POPHL, "POPHL", 1 },
        { &Cpu::LDIOCA, "LDIOCA", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::PUSHHL, "PUSHHL", 1 },
        { &Cpu::ANDn, "ANDn", 2 },
        { &Cpu::RST20, "RST20", 1 },
        { &Cpu::ADDSPn, "ADDSPn", 2 },
        { &Cpu::JPHL, "JPHL", 1 },
        { &Cpu::LDmmA, "LDmmA", 3 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::XORn, "XORn", 2 },
        { &Cpu::RST28, "RST28", 1 },

        // 0xF0
        { &Cpu::LDAIOn, "LDAIOn", 2 },
        { &Cpu::POPAF, "POPAF", 1 },
        { &Cpu::LDAIOC, "LDAIOC", 1 },
        { &Cpu::DI, "DI", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::PUSHAF, "PUSHAF", 1 },
        { &Cpu::ORn, "ORn", 2 },
        { &Cpu::RST30, "RST30", 1 },
        { &Cpu::LDHLSPn, "LDHLSPn", 2 },
        { &Cpu::LDSPHL, "LDSPHL", 3 },
        { &Cpu::LDAmm, "LDAmm", 3 },
        { &Cpu::EI, "EI", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::Unimpl, "XX", 1 },
        { &Cpu::CPn, "CPn", 2 },
        { &Cpu::RST38, "RST38", 1 },
};

Cpu::opinfo_t Cpu::cbopmap[256] = {
        // CB 0x00
        {&Cpu::RLCr_b, "RLCr_b", 1},
        {&Cpu::RLCr_c, "RLCr_c", 1},
        {&Cpu::RLCr_d, "RLCr_d", 1},
        {&Cpu::RLCr_e, "RLCr_e", 1},
        {&Cpu::RLCr_h, "RLCr_h", 1},
        {&Cpu::RLCr_l, "RLCr_l", 1},
        {&Cpu::RLCHL, "RLCHL", 1},
        {&Cpu::RLCr_a, "RLCr_a", 1},
        {&Cpu::RRCr_b, "RRCr_b", 1},
        {&Cpu::RRCr_c, "RRCr_c", 1},
        {&Cpu::RRCr_d, "RRCr_d", 1},
        {&Cpu::RRCr_e, "RRCr_e", 1},
        {&Cpu::RRCr_h, "RRCr_h", 1},
        {&Cpu::RRCr_l, "RRCr_l", 1},
        {&Cpu::RRCHL, "RRCHL", 1},
        {&Cpu::RRCr_a, "RRCr_a", 1},

        // CB 0x10
        {&Cpu::RLr_b, "RLr_b", 1},
        {&Cpu::RLr_c, "RLr_c", 1},
        {&Cpu::RLr_d, "RLr_d", 1},
        {&Cpu::RLr_e, "RLr_e", 1},
        {&Cpu::RLr_h, "RLr_h", 1},
        {&Cpu::RLr_l, "RLr_l", 1},
        {&Cpu::RLHL, "RLHL", 1},
        {&Cpu::RLr_a, "RLr_a", 1},
        {&Cpu::RRr_b, "RRr_b", 1},
        {&Cpu::RRr_c, "RRr_c", 1},
        {&Cpu::RRr_d, "RRr_d", 1},
        {&Cpu::RRr_e, "RRr_e", 1},
        {&Cpu::RRr_h, "RRr_h", 1},
        {&Cpu::RRr_l, "RRr_l", 1},
        {&Cpu::RRHL, "RRHL", 1},
        {&Cpu::RRr_a, "RRr_a", 1},

        // CB 0x20
        {&Cpu::SLAr_b, "SLAr_b", 1},
        {&Cpu::SLAr_c, "SLAr_c", 1},
        {&Cpu::SLAr_d, "SLAr_d", 1},
        {&Cpu::SLAr_e, "SLAr_e", 1},
        {&Cpu::SLAr_h, "SLAr_h", 1},
        {&Cpu::SLAr_l, "SLAr_l", 1},
        {&Cpu::SLAHL, "SLAHL", 1},
        {&Cpu::SLAr_a, "SLAr_a", 1},
        {&Cpu::SRAr_b, "SRAr_b", 1},
        {&Cpu::SRAr_c, "SRAr_c", 1},
        {&Cpu::SRAr_d, "SRAr_d", 1},
        {&Cpu::SRAr_e, "SRAr_e", 1},
        {&Cpu::SRAr_h, "SRAr_h", 1},
        {&Cpu::SRAr_l, "SRAr_l", 1},
        {&Cpu::SRAHL, "SRAHL", 1},
        {&Cpu::SRAr_a, "SRAr_a", 1},

        // CB 0x30
        {&Cpu::SWAPr_b, "SWAPr_b", 1},
        {&Cpu::SWAPr_c, "SWAPr_c", 1},
        {&Cpu::SWAPr_d, "SWAPr_d", 1},
        {&Cpu::SWAPr_e, "SWAPr_e", 1},
        {&Cpu::SWAPr_h, "SWAPr_h", 1},
        {&Cpu::SWAPr_l, "SWAPr_l", 1},
        {&Cpu::SWAPHL, "SWAPHL", 1},
        {&Cpu::SWAPr_a, "SWAPr_a", 1},
        {&Cpu::SRLr_b, "SRLr_b", 1},
        {&Cpu::SRLr_c, "SRLr_c", 1},
        {&Cpu::SRLr_d, "SRLr_d", 1},
        {&Cpu::SRLr_e, "SRLr_e", 1},
        {&Cpu::SRLr_h, "SRLr_h", 1},
        {&Cpu::SRLr_l, "SRLr_l", 1},
        {&Cpu::SRLHL, "SRLHL", 1},
        {&Cpu::SRLr_a, "SRLr_a", 1},

        // CB 0x40
        {&Cpu::BIT0b, "BIT0b", 1},
        {&Cpu::BIT0c, "BIT0c", 1},
        {&Cpu::BIT0d, "BIT0d", 1},
        {&Cpu::BIT0e, "BIT0e", 1},
        {&Cpu::BIT0h, "BIT0h", 1},
        {&Cpu::BIT0l, "BIT0l", 1},
        {&Cpu::BIT0m, "BIT0m", 1},
        {&Cpu::BIT0a, "BIT0a", 1},
        {&Cpu::BIT1b, "BIT1b", 1},
        {&Cpu::BIT1c, "BIT1c", 1},
        {&Cpu::BIT1d, "BIT1d", 1},
        {&Cpu::BIT1e, "BIT1e", 1},
        {&Cpu::BIT1h, "BIT1h", 1},
        {&Cpu::BIT1l, "BIT1l", 1},
        {&Cpu::BIT1m, "BIT1m", 1},
        {&Cpu::BIT1a, "BIT1a", 1},

        // CB 0x50
        {&Cpu::BIT2b, "BIT2b", 1},
        {&Cpu::BIT2c, "BIT2c", 1},
        {&Cpu::BIT2d, "BIT2d", 1},
        {&Cpu::BIT2e, "BIT2e", 1},
        {&Cpu::BIT2h, "BIT2h", 1},
        {&Cpu::BIT2l, "BIT2l", 1},
        {&Cpu::BIT2m, "BIT2m", 1},
        {&Cpu::BIT2a, "BIT2a", 1},
        {&Cpu::BIT3b, "BIT3b", 1},
        {&Cpu::BIT3c, "BIT3c", 1},
        {&Cpu::BIT3d, "BIT3d", 1},
        {&Cpu::BIT3e, "BIT3e", 1},
        {&Cpu::BIT3h, "BIT3h", 1},
        {&Cpu::BIT3l, "BIT3l", 1},
        {&Cpu::BIT3m, "BIT3m", 1},
        {&Cpu::BIT3a, "BIT3a", 1},

        // CB 0x60
        {&Cpu::BIT4b, "BIT4b", 1},
        {&Cpu::BIT4c, "BIT4c", 1},
        {&Cpu::BIT4d, "BIT4d", 1},
        {&Cpu::BIT4e, "BIT4e", 1},
        {&Cpu::BIT4h, "BIT4h", 1},
        {&Cpu::BIT4l, "BIT4l", 1},
        {&Cpu::BIT4m, "BIT4m", 1},
        {&Cpu::BIT4a, "BIT4a", 1},
        {&Cpu::BIT5b, "BIT5b", 1},
        {&Cpu::BIT5c, "BIT5c", 1},
        {&Cpu::BIT5d, "BIT5d", 1},
        {&Cpu::BIT5e, "BIT5e", 1},
        {&Cpu::BIT5h, "BIT5h", 1},
        {&Cpu::BIT5l, "BIT5l", 1},
        {&Cpu::BIT5m, "BIT5m", 1},
        {&Cpu::BIT5a, "BIT5a", 1},

        // CB 0x70
        {&Cpu::BIT6b, "BIT6b", 1},
        {&Cpu::BIT6c, "BIT6c", 1},
        {&Cpu::BIT6d, "BIT6d", 1},
        {&Cpu::BIT6e, "BIT6e", 1},
        {&Cpu::BIT6h, "BIT6h", 1},
        {&Cpu::BIT6l, "BIT6l", 1},
        {&Cpu::BIT6m, "BIT6m", 1},
        {&Cpu::BIT6a, "BIT6a", 1},
        {&Cpu::BIT7b, "BIT7b", 1},
        {&Cpu::BIT7c, "BIT7c", 1},
        {&Cpu::BIT7d, "BIT7d", 1},
        {&Cpu::BIT7e, "BIT7e", 1},
        {&Cpu::BIT7h, "BIT7h", 1},
        {&Cpu::BIT7l, "BIT7l", 1},
        {&Cpu::BIT7m, "BIT7m", 1},
        {&Cpu::BIT7a, "BIT7a", 1},

        // CB 0x80
        {&Cpu::RES0b, "RES0b", 1},
        {&Cpu::RES0c, "RES0c", 1},
        {&Cpu::RES0d, "RES0d", 1},
        {&Cpu::RES0e, "RES0e", 1},
        {&Cpu::RES0h, "RES0h", 1},
        {&Cpu::RES0l, "RES0l", 1},
        {&Cpu::RES0m, "RES0m", 1},
        {&Cpu::RES0a, "RES0a", 1},
        {&Cpu::RES1b, "RES1b", 1},
        {&Cpu::RES1c, "RES1c", 1},
        {&Cpu::RES1d, "RES1d", 1},
        {&Cpu::RES1e, "RES1e", 1},
        {&Cpu::RES1h, "RES1h", 1},
        {&Cpu::RES1l, "RES1l", 1},
        {&Cpu::RES1m, "RES1m", 1},
        {&Cpu::RES1a, "RES1a", 1},

        // CB 0x90
        {&Cpu::RES2b, "RES2b", 1},
        {&Cpu::RES2c, "RES2c", 1},
        {&Cpu::RES2d, "RES2d", 1},
        {&Cpu::RES2e, "RES2e", 1},
        {&Cpu::RES2h, "RES2h", 1},
        {&Cpu::RES2l, "RES2l", 1},
        {&Cpu::RES2m, "RES2m", 1},
        {&Cpu::RES2a, "RES2a", 1},
        {&Cpu::RES3b, "RES3b", 1},
        {&Cpu::RES3c, "RES3c", 1},
        {&Cpu::RES3d, "RES3d", 1},
        {&Cpu::RES3e, "RES3e", 1},
        {&Cpu::RES3h, "RES3h", 1},
        {&Cpu::RES3l, "RES3l", 1},
        {&Cpu::RES3m, "RES3m", 1},
        {&Cpu::RES3a, "RES3a", 1},

        // CB 0xA0
        {&Cpu::RES4b, "RES4b", 1},
        {&Cpu::RES4c, "RES4c", 1},
        {&Cpu::RES4d, "RES4d", 1},
        {&Cpu::RES4e, "RES4e", 1},
        {&Cpu::RES4h, "RES4h", 1},
        {&Cpu::RES4l, "RES4l", 1},
        {&Cpu::RES4m, "RES4m", 1},
        {&Cpu::RES4a, "RES4a", 1},
        {&Cpu::RES5b, "RES5b", 1},
        {&Cpu::RES5c, "RES5c", 1},
        {&Cpu::RES5d, "RES5d", 1},
        {&Cpu::RES5e, "RES5e", 1},
        {&Cpu::RES5h, "RES5h", 1},
        {&Cpu::RES5l, "RES5l", 1},
        {&Cpu::RES5m, "RES5m", 1},
        {&Cpu::RES5a, "RES5a", 1},

        // CB 0xB0
        {&Cpu::RES6b, "RES6b", 1},
        {&Cpu::RES6c, "RES6c", 1},
        {&Cpu::RES6d, "RES6d", 1},
        {&Cpu::RES6e, "RES6e", 1},
        {&Cpu::RES6h, "RES6h", 1},
        {&Cpu::RES6l, "RES6l", 1},
        {&Cpu::RES6m, "RES6m", 1},
        {&Cpu::RES6a, "RES6a", 1},
        {&Cpu::RES7b, "RES7b", 1},
        {&Cpu::RES7c, "RES7c", 1},
        {&Cpu::RES7d, "RES7d", 1},
        {&Cpu::RES7e, "RES7e", 1},
        {&Cpu::RES7h, "RES7h", 1},
        {&Cpu::RES7l, "RES7l", 1},
        {&Cpu::RES7m, "RES7m", 1},
        {&Cpu::RES7a, "RES7a", 1},

        // CB 0xC0
        {&Cpu::SET0b, "SET0b", 1},
        {&Cpu::SET0c, "SET0c", 1},
        {&Cpu::SET0d, "SET0d", 1},
        {&Cpu::SET0e, "SET0e", 1},
        {&Cpu::SET0h, "SET0h", 1},
        {&Cpu::SET0l, "SET0l", 1},
        {&Cpu::SET0m, "SET0m", 1},
        {&Cpu::SET0a, "SET0a", 1},
        {&Cpu::SET1b, "SET1b", 1},
        {&Cpu::SET1c, "SET1c", 1},
        {&Cpu::SET1d, "SET1d", 1},
        {&Cpu::SET1e, "SET1e", 1},
        {&Cpu::SET1h, "SET1h", 1},
        {&Cpu::SET1l, "SET1l", 1},
        {&Cpu::SET1m, "SET1m", 1},
        {&Cpu::SET1a, "SET1a", 1},

        // CB 0xD0
        {&Cpu::SET2b, "SET2b", 1},
        {&Cpu::SET2c, "SET2c", 1},
        {&Cpu::SET2d, "SET2d", 1},
        {&Cpu::SET2e, "SET2e", 1},
        {&Cpu::SET2h, "SET2h", 1},
        {&Cpu::SET2l, "SET2l", 1},
        {&Cpu::SET2m, "SET2m", 1},
        {&Cpu::SET2a, "SET2a", 1},
        {&Cpu::SET3b, "SET3b", 1},
        {&Cpu::SET3c, "SET3c", 1},
        {&Cpu::SET3d, "SET3d", 1},
        {&Cpu::SET3e, "SET3e", 1},
        {&Cpu::SET3h, "SET3h", 1},
        {&Cpu::SET3l, "SET3l", 1},
        {&Cpu::SET3m, "SET3m", 1},
        {&Cpu::SET3a, "SET3a", 1},

        // CB 0xE0
        {&Cpu::SET4b, "SET4b", 1},
        {&Cpu::SET4c, "SET4c", 1},
        {&Cpu::SET4d, "SET4d", 1},
        {&Cpu::SET4e, "SET4e", 1},
        {&Cpu::SET4h, "SET4h", 1},
        {&Cpu::SET4l, "SET4l", 1},
        {&Cpu::SET4m, "SET4m", 1},
        {&Cpu::SET4a, "SET4a", 1},
        {&Cpu::SET5b, "SET5b", 1},
        {&Cpu::SET5c, "SET5c", 1},
        {&Cpu::SET5d, "SET5d", 1},
        {&Cpu::SET5e, "SET5e", 1},
        {&Cpu::SET5h, "SET5h", 1},
        {&Cpu::SET5l, "SET5l", 1},
        {&Cpu::SET5m, "SET5m", 1},
        {&Cpu::SET5a, "SET5a", 1},

        // CB 0xF0
        {&Cpu::SET6b, "SET6b", 1},
        {&Cpu::SET6c, "SET6c", 1},
        {&Cpu::SET6d, "SET6d", 1},
        {&Cpu::SET6e, "SET6e", 1},
        {&Cpu::SET6h, "SET6h", 1},
        {&Cpu::SET6l, "SET6l", 1},
        {&Cpu::SET6m, "SET6m", 1},
        {&Cpu::SET6a, "SET6a", 1},
        {&Cpu::SET7b, "SET7b", 1},
        {&Cpu::SET7c, "SET7c", 1},
        {&Cpu::SET7d, "SET7d", 1},
        {&Cpu::SET7e, "SET7e", 1},
        {&Cpu::SET7h, "SET7h", 1},
        {&Cpu::SET7l, "SET7l", 1},
        {&Cpu::SET7m, "SET7m", 1},
        {&Cpu::SET7a, "SET7a", 1},

};
